# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(010001)
$foreground = rgb(ECE8DB)
$color0 = rgb(010001)
$color1 = rgb(2C2A2D)
$color2 = rgb(2F2E33)
$color3 = rgb(504D40)
$color4 = rgb(4D5766)
$color5 = rgb(607188)
$color6 = rgb(968E71)
$color7 = rgb(DBD6C2)
$color8 = rgb(999688)
$color9 = rgb(3B383C)
$color10 = rgb(3F3E44)
$color11 = rgb(6A6655)
$color12 = rgb(667388)
$color13 = rgb(8097B5)
$color14 = rgb(C8BE97)
$color15 = rgb(DBD6C2)
