# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(18191B)
$foreground = rgb(F6F5F2)
$color0 = rgb(3F4042)
$color1 = rgb(0E1418)
$color2 = rgb(13477A)
$color3 = rgb(A73266)
$color4 = rgb(5E8AA0)
$color5 = rgb(B6AA0F)
$color6 = rgb(ADA9A4)
$color7 = rgb(EAE8E4)
$color8 = rgb(A4A2A0)
$color9 = rgb(131A20)
$color10 = rgb(195EA3)
$color11 = rgb(DE4388)
$color12 = rgb(7DB8D5)
$color13 = rgb(F3E214)
$color14 = rgb(E6E1DA)
$color15 = rgb(EAE8E4)
