font_family        monospace
font_size          12

background_opacity 0.9
allow_remote_control yes
shell              /usr/bin/zsh

map ctrl+backspace    delete_word_backward
map ctrl+shift+v      paste_from_clipboard
map ctrl+shift+c      copy_to_clipboard
map ctrl+shift+f      toggle_fullscreen


foreground           #f0d9b5
background           #0d1520

selection_background #FF6B00
selection_foreground #0d1520

cursor               #FF9320
cursor_text_color    #0d1520

url_color            #5ba3c9

active_border_color   #FF9320
inactive_border_color #1e2a3a

active_tab_foreground   #0d1520
active_tab_background   #FF6B00
inactive_tab_foreground #f0d9b5
inactive_tab_background #1e2a3a

color0   #0d1520   # black
color1   #cc3333   # red
color2   #7aab5a   # green
color3   #FFB347   # yellow
color4   #5ba3c9   # blue
color5   #b87aaa   # magenta
color6   #FF8C42   # cyan
color7   #c8b89a   # white

color8   #1e2a3a   # bright black
color9   #ff5555   # bright red
color10  #98c97a   # bright green
color11  #FFD080   # bright yellow
color12  #80bfdd   # bright blue
color13  #d4a0c8   # bright magenta
color14  #FFB060   # bright cyan
color15  #f0d9b5   # bright white
