# override default search paths (~/ ~/personal ~/personal/dev/env/.config)
TS_SEARCH_PATHS=(~/dev)

# Session commands: M-h = -s 0, M-t = -s 1, M-n = -s 2, M-s = -s 3
# Каждая команда запускается в отдельном окне (индекс 69+)
TS_SESSION_COMMANDS=(lazygit lazydocker)
